language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - export PATH="/home/travis/.cask/bin:$PATH"

  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.githubusercontent.com/cask/cask/master/go | python
  - cask

env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest-travis
  - EVM_EMACS=emacs-git-snapshot-travis

install:
  - pip install importmagic
  - pip install epc

script:
  - cask exec ecukes

notifications:
  email:
    on_success: never
    on_failure: always
